#base image to build off of
FROM rocker/rstudio:4.4.2

#installing the remotes package first
RUN Rscript -e "install.packages('remotes')"

#installing specific version of a package
#going to install gapminder package, version 1.0.0
RUN Rscript -e "remotes::install_version('gapminder', '1.0.0')"



